server:
  port: 2100
  forward-headers-strategy: framework
spring:
  application:
    name: businessconfig

operatorfabric.businessconfig:
  storage:
    path: "./services/core/businessconfig/build/docker-volume/businessconfig-storage"

#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: http://localhost:2103
